### ISSUE TITLE
Head is reset every time while adding

### ISSUE THREAD

**Issue by morpheusx3** [morpheusx3/Computing-II-Final#1]
Every time add() is run, the head is set to the most recent addition to the list. I have no idea why this happens.

**Comment by RoseGreeley** [comment]
Are we not adding to the head? Do you mean list or Queue?
-Rose 


     On Thursday, April 16, 2015 5:43 PM, Darrien Glasser <notifications@github.com> wrote:
   

 Every time add is run, the head is set to the most recent addition to the list. I have no idea why this happens.—

**Comment by morpheusx3** [comment]
I was a little rushed when I put that issue up. I definitely should have clarified better.

This deals with the Linked List, and head, along with everything else is overwritten upon adding a new item.

**Comment by RoseGreeley** [comment]
I'm not looking at the code, but it could be that we assign it to the head before saying it's next is what is currently the head.

I'll look at it in about two hours when I get home!

-Rose
